### PR TITLE
Added werman/noise-suppression-for-voice to EqualizerAPO

### PR DESCRIPTION
**Pull request by nico54w**
### Script yet to be tested

Adding werman/noise-suppression-for-voice VST plugin to equalizerAPO.

May require some tweaks, to get a better voice quality.

Script yet to be tested. Sorry.

### CODE REVIEW

**Comment by CelesteHeartsong** [comment]
Let me run this by a few people.  I don't know if we would want to add noise suppression to the default audio configuration if it would come at the expense of overall audio fidelity.

**Comment by syberphunk** [comment]
Can this script instead look for and pull the latest version rather than grabbing a fixed v1.03 ?

-URI "https://github.com/werman/noise-suppression-for-voice/releases/download/v1.03/win-rnnoise.zip"

**Comment by CelesteHeartsong** [comment]
DLL being loaded looks clean: https://www.virustotal.com/gui/file/1d53e1c8d44c03767cfe7e64c33ffe0c13f73c34dfd70af9c1f1010eef32a9d4/detection

I don't mind just loading a static version for now,  just in case future updates cause issues on the hardware.  I know there's been a lot of work on SteamDeckTools that hopeful comes to a stable release soon and I can merge both that and this VST plugin at the same time.

**Comment by nico54w** [comment]
This is a really fast change I did to play online games with voice chat, improvements I will try latter are: 
1. Better plugin configuration.
2. A recommended mic volume.
Btw, I didn't know I could set the download to latest.
Originally the configuration added by the plugin sets up a device identification path at the end of "And microphone" in the apo config file, but seems to work fine without it. Hope this doesn't makes any error.

**Review by CelesteHeartsong — APPROVED** [review]

**Comment by CelesteHeartsong** [comment]
Approved merge, APU driver updated so I'll be doing some test runs in the next few days.  I'll report back in if I find that anything goes awry on a fresh install.

**Pull request merged**
